- windrose/windrose.py
Should replace https://github.com/scls19fr/windrose/pull/16 and https://github.com/scls19fr/windrose/pull/22 
and fix https://github.com/scls19fr/windrose/issues/17
> Add locale support for speed (var) intervals

- .travis.yml
- requirements-dev.txt
- requirements.txt
> Faster (working) Travis-CI.

- windrose/windrose.py
#27 - added optional argument decimal_places in legend function to show legend bins with decimal places different of 1
> added optional argument decimal_places

- .gitignore
- samples/example_statistical_input.py
- windrose/windrose.py
closes https://github.com/scls19fr/windrose/issues/49
> Fix mpl2 warning

- windrose/windrose.py
This allows to do stuff like:
```python
leg = ax.set_legend()
leg.get_frame().set_alpha(1)
```
> set_legend should return the legend instance

- .travis.yml
- samples/example_animate.py
- samples/example_by.py
- samples/example_np_mpl_oo.py
- samples/example_pandas.py
- samples/example_pdf_by.py
- samples/example_subplots.py
- setup.py
- windrose/windrose.py
PEP8
Remove Python 3.3 support
> Fix CI for Python 2.7 3.4 3.5 3.6

- setup.py
> Fix license issue in setup.py

- paper.md
xref.: https://github.com/python-windrose/windrose/issues/54#issuecomment-388318826
> Update ocefpaf's affiliation

- docs/development.rst
- setup.py
- tests/test_windrose.py
Closes https://github.com/python-windrose/windrose/issues/88
> remove all mentions of nose

- paper/paper.md
This is a simple typo fix.
PS : I'm glade to be the 100th PR !!
> fix typo in paper.md

- windrose/windrose.py
Took answer from @anntzer: https://github.com/matplotlib/matplotlib/issues/11911#issuecomment-414982843
Resolves #81; resolves #37.
> Remove use of pylab.poly_between

- windrose/windrose.py
> add custom units to the legend

- .gitignore
- tests/test_windrose.py
Some little improvements for the test part.
> Improve testing

- windrose/windrose.py
I ran into an issue when trying to instantiate an axe. I then propose the following fix that worked for me.
> fix theta_labels kwarg pop

- .binder/environment.yml
- README.md
- setup.cfg
Closes https://github.com/python-windrose/windrose/issues/63
> Add binder environment and badge

- docs/conf.py
> Language cannot be empty

- docs/development.rst
- docs/install.rst
Minor development install updates.
> Update install docs

- windrose/windrose.py
> use mpl default cmap

- .github/dependabot.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/pypi.yml
- .github/workflows/tests.yml
Also update the GHA and add py311 to the test matrix.
> add dependabot and update GHA

- .github/workflows/deploy-docs.yml
- .github/workflows/pypi.yml
- .github/workflows/tests.yml
Using mamba-org/setup-micromamba@v1 instead.
> provision-with-micromamba is deprecated

- windrose/windrose.py
This fixes #271 in my case. Thanks for addressing this
> fix for incompatibility with numpy 2

- .pre-commit-config.yaml
- pyproject.toml
> update pre-commits and ignore print in notebook
