python-windrose/windrose

.travis.yml, samples/example_subplots.py, windrose/__init__.py, windrose/windrose.py
=> Register projection windrose

windrose/windrose.py
Users may wish to send options to pyplot's legend() function, e.g. `ax.set_legend(loc='upper center')`
=> Allow sending options to pyplot's legend()

setup.py
PyPI will soon support markdown files making this dependency unnecessary.
See https://packaging.python.org/specifications/#description-content-type
=> no setuptools-markdown

.gitignore, .travis.yml, requirements-dev.txt
The important changes here are:
- use the `conda-forge` channel instead of deprecated `ioos` channel;
- switched the test call to `pytest` b/c `nose` is also deprecated;
- ~~moved the `flake8` tests to a `coding_standards` block matrix and let that "fail" b/c we rarely want coding standards to be a hard failure.~~
=> Modernize Travis-CI

windrose/windrose.py
The Nbins parameter wasn't properly forwarded to the `pdf` method, so `wrpdf` only respected `bins` for customisation.
=> Pass Nbins from wrpdf to WindAxes.pdf

.travis.yml, CHANGELOG.md, Untitled.ipynb, windrose/version.py
We need a new release to take into account the change in master that resolv: https://github.com/python-windrose/windrose/issues/136, https://github.com/python-windrose/windrose/issues/119 and https://github.com/python-windrose/windrose/issues/135 .
=> Bump version 1.6.8

windrose/windrose.py
function clean() has direction/var ordering but was called in plot_windrose_np() as var/direction. 
Closes #155
=> Fix variable calling/returning order

windrose/windrose.py
I encountered a deprecation warning from numpy:
```
DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
dir_bins = np.arange(-angle / 2, 360. + angle, angle, dtype=np.float)
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
simply replacing `numpy.float` with the built in `float` should fix this.
=> fix np.float deprecation warning

setup.cfg
Forgot this in #178. The code is py>=3.6 for a while now and we cannot build a universal wheel that would be installable in py2k.
=> We no longer support Python 2k, so no universal wheel

.github/workflows/deploy-docs.yml
For some reason the gh-pages were not activated and we were also publishing docs in every merge. This will fix the latter by publishing only when there is a new tag and I fixed the former in the settings.
=> fix gh-pages publication

.pre-commit-config.yaml, requirements.txt, setup.cfg, windrose/windrose.py
This should work with mpl >=3 b/c too, I updated the minimum requirement.
Closes #190
=> Fix issue with matplotlib 3.6.0

docs/index.rst, notebooks/windrose_sample_poitiers_csv.ipynb
@scls19fr the depsy badge doesn't have an https version and GH doesn't render it. Are you OK removing it?
=> remove broken badge link

README.md
The read the docs build has been broken for a while and I don't have access to fix it. We did implement a gh-pages a while back and that one is building automatically every new tagged release using GitHub Actions.
=> remove read the docs badge

windrose/windrose.py
this fixes a deprecation warning for using the `matplotlib.doctstring` module and the `copy` decorator. I simply added the decorator as a private part.
this also fixes a deprecation warning for passing `loc` as a positional argument to `legend.Legend`
=> fix matplotlib deprecation warnings

.github/workflows/tests.yml
This will save us a lot of headaches with mpl's deprecation. It will fail here but should pass with #201
=> error out on warnings

.pre-commit-config.yaml
Skipping this word b/c we should not edit the license file.
=> skip codespell on therefor

requirements.txt, setup.cfg, windrose/windrose.py
the package is currently broken with numpy>1.23 since `histogram2d` removed the `normed` argument (release notes: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations, pull request: https://github.com/numpy/numpy/pull/21645)
the docs and release notes just suggest using `density` as a drop in replacement instead (that's what the PR does)
for `numpy.histogram` it is already correct: https://github.com/python-windrose/windrose/blob/d05f76eb51478aab12a0a026961dffe5db9a32c4/windrose/windrose.py#L748
EDIT: we should probably also make a release after this to fix installations from PyPi (usually people shouldn't have `numpy` pinned)
=> fix compatibility issue with numpy 1.24

.github/workflows/pypi.yml
Last release the publishing failed b/c I forgot to add this change.
=> minor fix to the pypi GHA

README.md
The link to the contributors file in the README still pointed to master but that was renamed to main.
=> Rename branch to main in link to contributors list

README.md, docs/conf.py, docs/index.rst, docs/install.rst, notebooks/usage.ipynb, requirements-dev.txt
- also add a copy button to all code block for easier usage of the docs
I think there were some issues deploying the docs in the past - they don't seem to be up to date with what's in the repo. I couldn't test the deploy workflow, but building works fine for me now (locally and in gha).
The docs used to have a subplots example, which unfortunately was broken and also quite complex. I think the most straight forward way to use this with subplots is `seaborn`.
In general I think subplots are commonly used and having an easy way of creating them in the docs is nice, since windroses in general lack the temporal component.
- resolves #224
- resolves #26 (maybe? why should we reinvent the wheel?)
This is the output of the example:
=> fix the docs build and add an easy example for subplots using seaborn

windrose/windrose.py
Now it checks if ``bins`` list has any ``NaN`` values, then it throws a detailed error. Hopefully, this fits the overall style of the package.
=> check input bins validity issue #268
